"""updated card

Revision ID: b3af7882250b
Revises: 8c7d428d50a8
Create Date: 2024-06-15 02:36:03.570565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3af7882250b'
down_revision: Union[str, None] = '8c7d428d50a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('card', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('card', sa.Column('deadline', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'deadline')
    op.drop_column('card', 'updated')
    op.drop_column('card', 'created')
    # ### end Alembic commands ###
